spring.application.name=horse-racing-management-system

server.port=8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/horse_racing_management_system
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false



#Email Verificatio
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tringuyencao33@gmail.com
spring.mail.password=behq cctn zuew cfty

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=localhost
spring.data.redis.port=6379


#Spring Security
spring.security.user.name=caotri
spring.security.user.password=12345

app.jwt.secret=dGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9yVGhlT25saW5lRXlld2VhclN5c3RlbQ==
app.jwt.expiration=86400000

# Multipart upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB